// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/game.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.10.0';

  @override
  int get rustContentHash => 1565766477;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_tac_tics',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<GridPosition> crateApiGameUtttGameAiPlay({
    required UtttGame that,
    required List<GridPosition> availableMove,
    required bool crossPlaying,
  });

  int crateApiGameUtttGameAutoAccessorGetBigGame({required UtttGame that});

  BigInt crateApiGameUtttGameAutoAccessorGetCrosses({required UtttGame that});

  BigInt crateApiGameUtttGameAutoAccessorGetNoughts({required UtttGame that});

  GameState crateApiGameUtttGameAutoAccessorGetState({required UtttGame that});

  void crateApiGameUtttGameAutoAccessorSetBigGame({
    required UtttGame that,
    required int bigGame,
  });

  void crateApiGameUtttGameAutoAccessorSetCrosses({
    required UtttGame that,
    required BigInt crosses,
  });

  void crateApiGameUtttGameAutoAccessorSetNoughts({
    required UtttGame that,
    required BigInt noughts,
  });

  void crateApiGameUtttGameAutoAccessorSetState({
    required UtttGame that,
    required GameState state,
  });

  Future<UtttGame> crateApiGameUtttGameNew();

  Future<List<GridPosition>> crateApiGameUtttGamePlay({
    required UtttGame that,
    required GridPosition cell,
    required bool crossPlaying,
  });

  Future<void> crateApiGameUtttGameUndo({
    required UtttGame that,
    required GridPosition cell,
    required bool crossMove,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_UtttGame;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_UtttGame;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_UtttGamePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<GridPosition> crateApiGameUtttGameAiPlay({
    required UtttGame that,
    required List<GridPosition> availableMove,
    required bool crossPlaying,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUTTTGame(
            that,
            serializer,
          );
          sse_encode_list_grid_position(availableMove, serializer);
          sse_encode_bool(crossPlaying, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_grid_position,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGameUtttGameAiPlayConstMeta,
        argValues: [that, availableMove, crossPlaying],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGameUtttGameAiPlayConstMeta => const TaskConstMeta(
    debugName: "UtttGame_ai_play",
    argNames: ["that", "availableMove", "crossPlaying"],
  );

  @override
  int crateApiGameUtttGameAutoAccessorGetBigGame({required UtttGame that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUTTTGame(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGameUtttGameAutoAccessorGetBigGameConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGameUtttGameAutoAccessorGetBigGameConstMeta =>
      const TaskConstMeta(
        debugName: "UtttGame_auto_accessor_get_big_game",
        argNames: ["that"],
      );

  @override
  BigInt crateApiGameUtttGameAutoAccessorGetCrosses({required UtttGame that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUTTTGame(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_U128,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGameUtttGameAutoAccessorGetCrossesConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGameUtttGameAutoAccessorGetCrossesConstMeta =>
      const TaskConstMeta(
        debugName: "UtttGame_auto_accessor_get_crosses",
        argNames: ["that"],
      );

  @override
  BigInt crateApiGameUtttGameAutoAccessorGetNoughts({required UtttGame that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUTTTGame(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_U128,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGameUtttGameAutoAccessorGetNoughtsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGameUtttGameAutoAccessorGetNoughtsConstMeta =>
      const TaskConstMeta(
        debugName: "UtttGame_auto_accessor_get_noughts",
        argNames: ["that"],
      );

  @override
  GameState crateApiGameUtttGameAutoAccessorGetState({required UtttGame that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUTTTGame(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_game_state,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGameUtttGameAutoAccessorGetStateConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGameUtttGameAutoAccessorGetStateConstMeta =>
      const TaskConstMeta(
        debugName: "UtttGame_auto_accessor_get_state",
        argNames: ["that"],
      );

  @override
  void crateApiGameUtttGameAutoAccessorSetBigGame({
    required UtttGame that,
    required int bigGame,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUTTTGame(
            that,
            serializer,
          );
          sse_encode_u_32(bigGame, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGameUtttGameAutoAccessorSetBigGameConstMeta,
        argValues: [that, bigGame],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGameUtttGameAutoAccessorSetBigGameConstMeta =>
      const TaskConstMeta(
        debugName: "UtttGame_auto_accessor_set_big_game",
        argNames: ["that", "bigGame"],
      );

  @override
  void crateApiGameUtttGameAutoAccessorSetCrosses({
    required UtttGame that,
    required BigInt crosses,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUTTTGame(
            that,
            serializer,
          );
          sse_encode_U128(crosses, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGameUtttGameAutoAccessorSetCrossesConstMeta,
        argValues: [that, crosses],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGameUtttGameAutoAccessorSetCrossesConstMeta =>
      const TaskConstMeta(
        debugName: "UtttGame_auto_accessor_set_crosses",
        argNames: ["that", "crosses"],
      );

  @override
  void crateApiGameUtttGameAutoAccessorSetNoughts({
    required UtttGame that,
    required BigInt noughts,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUTTTGame(
            that,
            serializer,
          );
          sse_encode_U128(noughts, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGameUtttGameAutoAccessorSetNoughtsConstMeta,
        argValues: [that, noughts],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGameUtttGameAutoAccessorSetNoughtsConstMeta =>
      const TaskConstMeta(
        debugName: "UtttGame_auto_accessor_set_noughts",
        argNames: ["that", "noughts"],
      );

  @override
  void crateApiGameUtttGameAutoAccessorSetState({
    required UtttGame that,
    required GameState state,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUTTTGame(
            that,
            serializer,
          );
          sse_encode_game_state(state, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGameUtttGameAutoAccessorSetStateConstMeta,
        argValues: [that, state],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGameUtttGameAutoAccessorSetStateConstMeta =>
      const TaskConstMeta(
        debugName: "UtttGame_auto_accessor_set_state",
        argNames: ["that", "state"],
      );

  @override
  Future<UtttGame> crateApiGameUtttGameNew() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUTTTGame,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGameUtttGameNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGameUtttGameNewConstMeta =>
      const TaskConstMeta(debugName: "UtttGame_new", argNames: []);

  @override
  Future<List<GridPosition>> crateApiGameUtttGamePlay({
    required UtttGame that,
    required GridPosition cell,
    required bool crossPlaying,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUTTTGame(
            that,
            serializer,
          );
          sse_encode_box_autoadd_grid_position(cell, serializer);
          sse_encode_bool(crossPlaying, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_grid_position,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGameUtttGamePlayConstMeta,
        argValues: [that, cell, crossPlaying],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGameUtttGamePlayConstMeta => const TaskConstMeta(
    debugName: "UtttGame_play",
    argNames: ["that", "cell", "crossPlaying"],
  );

  @override
  Future<void> crateApiGameUtttGameUndo({
    required UtttGame that,
    required GridPosition cell,
    required bool crossMove,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUTTTGame(
            that,
            serializer,
          );
          sse_encode_box_autoadd_grid_position(cell, serializer);
          sse_encode_bool(crossMove, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGameUtttGameUndoConstMeta,
        argValues: [that, cell, crossMove],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGameUtttGameUndoConstMeta => const TaskConstMeta(
    debugName: "UtttGame_undo",
    argNames: ["that", "cell", "crossMove"],
  );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_UtttGame => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUTTTGame;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_UtttGame => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUTTTGame;

  @protected
  UtttGame
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUTTTGame(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return UtttGameImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  UtttGame
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUTTTGame(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return UtttGameImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  UtttGame
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUTTTGame(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return UtttGameImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  UtttGame
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUTTTGame(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return UtttGameImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BigInt dco_decode_U128(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BigInt.parse(raw);
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  GridPosition dco_decode_box_autoadd_grid_position(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_grid_position(raw);
  }

  @protected
  GameState dco_decode_game_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GameState.values[raw as int];
  }

  @protected
  GridPosition dco_decode_grid_position(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return GridPosition(
      grid: dco_decode_u_16(arr[0]),
      posInGrid: dco_decode_u_16(arr[1]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<GridPosition> dco_decode_list_grid_position(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_grid_position).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  UtttGame
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUTTTGame(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return UtttGameImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  UtttGame
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUTTTGame(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return UtttGameImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  UtttGame
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUTTTGame(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return UtttGameImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  UtttGame
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUTTTGame(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return UtttGameImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BigInt sse_decode_U128(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return BigInt.parse(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  GridPosition sse_decode_box_autoadd_grid_position(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_grid_position(deserializer));
  }

  @protected
  GameState sse_decode_game_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return GameState.values[inner];
  }

  @protected
  GridPosition sse_decode_grid_position(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_grid = sse_decode_u_16(deserializer);
    var var_posInGrid = sse_decode_u_16(deserializer);
    return GridPosition(grid: var_grid, posInGrid: var_posInGrid);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<GridPosition> sse_decode_list_grid_position(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <GridPosition>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_grid_position(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUTTTGame(
    UtttGame self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as UtttGameImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUTTTGame(
    UtttGame self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as UtttGameImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUTTTGame(
    UtttGame self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as UtttGameImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUTTTGame(
    UtttGame self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as UtttGameImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_U128(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.toString(), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_grid_position(
    GridPosition self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_grid_position(self, serializer);
  }

  @protected
  void sse_encode_game_state(GameState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_grid_position(GridPosition self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.grid, serializer);
    sse_encode_u_16(self.posInGrid, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_grid_position(
    List<GridPosition> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_grid_position(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class UtttGameImpl extends RustOpaque implements UtttGame {
  // Not to be used by end users
  UtttGameImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  UtttGameImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_UtttGame,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_UtttGame,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_UtttGamePtr,
  );

  Future<GridPosition> aiPlay({
    required List<GridPosition> availableMove,
    required bool crossPlaying,
  }) => RustLib.instance.api.crateApiGameUtttGameAiPlay(
    that: this,
    availableMove: availableMove,
    crossPlaying: crossPlaying,
  );

  int get bigGame => RustLib.instance.api
      .crateApiGameUtttGameAutoAccessorGetBigGame(that: this);

  BigInt get crosses => RustLib.instance.api
      .crateApiGameUtttGameAutoAccessorGetCrosses(that: this);

  BigInt get noughts => RustLib.instance.api
      .crateApiGameUtttGameAutoAccessorGetNoughts(that: this);

  GameState get state =>
      RustLib.instance.api.crateApiGameUtttGameAutoAccessorGetState(that: this);

  set bigGame(int bigGame) => RustLib.instance.api
      .crateApiGameUtttGameAutoAccessorSetBigGame(that: this, bigGame: bigGame);

  set crosses(BigInt crosses) => RustLib.instance.api
      .crateApiGameUtttGameAutoAccessorSetCrosses(that: this, crosses: crosses);

  set noughts(BigInt noughts) => RustLib.instance.api
      .crateApiGameUtttGameAutoAccessorSetNoughts(that: this, noughts: noughts);

  set state(GameState state) => RustLib.instance.api
      .crateApiGameUtttGameAutoAccessorSetState(that: this, state: state);

  Future<List<GridPosition>> play({
    required GridPosition cell,
    required bool crossPlaying,
  }) => RustLib.instance.api.crateApiGameUtttGamePlay(
    that: this,
    cell: cell,
    crossPlaying: crossPlaying,
  );

  Future<void> undo({required GridPosition cell, required bool crossMove}) =>
      RustLib.instance.api.crateApiGameUtttGameUndo(
        that: this,
        cell: cell,
        crossMove: crossMove,
      );
}
