// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `check_single_win`, `check_win`, `u128_to_binary_string`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<UTTTGame>>
abstract class UtttGame implements RustOpaqueInterface {
  Future<GridPosition> aiPlay({
    required List<GridPosition> availableMove,
    required bool crossPlaying,
  });

  int get bigGame;

  BigInt get crosses;

  BigInt get noughts;

  GameState get state;

  set bigGame(int bigGame);

  set crosses(BigInt crosses);

  set noughts(BigInt noughts);

  set state(GameState state);

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<UtttGame> newInstance() =>
      RustLib.instance.api.crateApiGameUtttGameNew();

  Future<List<GridPosition>> play({
    required GridPosition cell,
    required bool crossPlaying,
  });

  Future<void> undo({required GridPosition cell, required bool crossMove});
}

enum GameState { crosssesWin, noughtsWin, tie, crossesTurn, noughtsTurn }

class GridPosition {
  final int grid;
  final int posInGrid;

  const GridPosition({required this.grid, required this.posInGrid});

  @override
  int get hashCode => grid.hashCode ^ posInGrid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GridPosition &&
          runtimeType == other.runtimeType &&
          grid == other.grid &&
          posInGrid == other.posInGrid;
}
